Add cidaas provider
oauth2-proxy/oauth2-proxy pull request #2273
Opened 2023-10-18 08:11 UTC by Bibob7

This Pull Request add a new Provider for the [Cidaas IDP](https://www.cidaas.com).

## Description

Just add a new Provider type

## Motivation and Context

Cidaas offers the usual OIDC flow, but the way how groups and roles are provided is special. Because of this, I added a formatting function to translate it into a valid format for the SessionState.

## How Has This Been Tested?

I added tests for the new provider type and also use it already in our system.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

2023-10-23 15:11 UTC, kvanzuijlen requested changes, later dismissed
Can you add some docs please?

Also, is there a specific reason why the OIDC provider wouldn't suffice for this provider; what does this add that wasn't already possible with the OIDC provider?

2023-11-18 14:57 UTC, JoelSpeed commented
> Cidaas offers the usual OIDC flow, but the way how groups and roles are provided is special. Because of this, I added a formatting function to translate it into a valid format for the SessionState.

Can you expand on how the groups work for me please? I'm wondering if there's a way to handle this more generically for each provider that has a different group format, rather than overloading what we already have

2024-08-20 16:47 UTC, Teko012 commented
Hi @kvanzuijlen @JoelSpeed @tuunit! I was looking into getting back to this PR, so it can be merged. If you got clarification on these questions, and a rebase, are you open to get this merged still? I just wanna make sure we are not wasting time :) Thank you in advance!

2024-08-20 17:04 UTC, tuunit requested changes
Sorry that his PR was sitting on the sidelines for so long. Overall the code quality looks good. Please fix the sorting and merge / rebase conflicts and then we will rerun the CI

2024-08-20 17:04 UTC, tuunit commented on pkg/apis/options/providers.go
> +	CidaasProvider ProviderType = "cidaas"
This struct is alphabetically sorted. Please move the provider in-between bitbucket and DO

2024-08-20 17:04 UTC, tuunit commented on providers/providers.go
> +	case options.ADFSProvider, options.AzureProvider, options.GitLabProvider, options.KeycloakOIDCProvider, options.OIDCProvider, options.CidaasProvider:
same goes for this case statement please move it in-between azure and gitlab

2024-08-20 17:04 UTC, tuunit commented
@Teko012 thanks for reminding me of this PR

2024-10-21 21:59 UTC, Teko012 commented
This is still a work in progress.

2025-01-12 12:27 UTC, tuunit commented
@Teko012 @Bibob7 is this ready for a final review and merge?

2025-01-12 12:40 UTC, tuunit requested changes

2025-01-12 12:40 UTC, tuunit commented on providers/cidaas.go
> +	}
```suggestion
	if err := p.redeemRefreshToken(ctx, s); err != nil {
		return false, fmt.Errorf("unable to redeem refresh token: %w", err)
	}
	
	if err := p.EnrichSession(ctx, s); err != nil {
		return false, fmt.Errorf("unable to enrich session data after refresh: %w %v", err, s)
	}
```

2025-01-12 12:40 UTC, tuunit commented on providers/cidaas.go
> +	}
less deep nesting

```suggestion
	if p.ProfileURL.String() == "" && s.Email == "" {
		return errors.New("id_token did not contain an email and profileURL is not defined")
	} else if p.ProfileURL.String() == "" {
			return nil
	}
```

2025-01-12 12:40 UTC, tuunit commented on providers/cidaas.go
> +	}
```suggestion
	if err := p.enrichFromUserinfoEndpoint(ctx, s); err != nil {
		logger.Errorf("Warning: Profile URL request failed: %w", err)
	}
```

2025-01-12 12:40 UTC, tuunit commented on providers/cidaas.go
> +	var groupsClaimList GroupsClaimList
```suggestion
	}
	
	var groupsClaimList GroupsClaimList
```

2025-01-12 12:40 UTC, tuunit commented on providers/providers.go
> +		return NewCIDAASProvider(providerData), nil
```suggestion
		return NewCIDAASProvider(providerData, providerConfig), nil
```

2025-01-12 12:40 UTC, tuunit commented on providers/cidaas.go
> +func NewCIDAASProvider(p *ProviderData) *CIDAASProvider {
```suggestion
func NewCIDAASProvider(p *ProviderData, opts options.Provider) *CIDAASProvider {
```

2025-01-12 12:40 UTC, tuunit commented on providers/cidaas.go
> +	}
```suggestion

  opts.InsecureSkipNonce = true // Should this be configurable or not?! Do you need to skip the nonce for Cidaas?
  
	return &CIDAASProvider{
		OIDCProvider: NewOIDCProvider(p, opts.OIDCConfig),
	}
```

2025-07-16 19:17 UTC, tuunit commented
@Bibob7 I want to get this merged finally... Last but not least can you add a documentation page for the provider?

2025-07-21 13:23 UTC, Bibob7 commented
@tuunit  @kvanzuijlen: I added the requested doc page. Please go ahead.

2025-08-01 16:42 UTC, tuunit submitted a review, later dismissed
LGTM

2025-08-04 14:49 UTC, Teko012 commented
Thanks. @tuunit can you merge it?

2025-08-12 15:41 UTC, tuunit approved these changes

2025-08-12 15:41 UTC, merged