Add possibility to encode the state param as UrlEncodedBase64
oauth2-proxy/oauth2-proxy pull request #2312
Opened 2023-11-07 12:23 UTC by brezinajn

## Description

This is continuation of #2239

Added a feature to optionally Base64Url encode the state param.
The feature is behind a configuration flag, so the default behavior remains unchanged.

## Motivation and Context

We're facing an issue where the state parameter gets truncated by the provider, leading to an incorrect application state after login. It's probably [this](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/adfs.go#L59) issue but in our case with an oidc provider.

## How Has This Been Tested?

We used a build from this commit as a drop-in replacement for 7.5.0 on our testing environment. Works as expected.

## Checklist:

- [x] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.
- [x] I have written tests for my code changes.

2023-11-20 21:39 UTC, tuunit approved these changes

2023-11-25 11:18 UTC, JoelSpeed submitted a review, later dismissed
I'm ok with this. I think though when we go through the alpha config migration to GA, I would probably suggest changing up the bool to an enum.

Something like `stateEncoding: Plain | Base64` would be more flexible and allow us to add additional options in the future should we choose to do so.

2023-11-25 11:19 UTC, JoelSpeed commented
Looks like there's a conflict that will need to be resolved before we merge

2023-11-27 09:40 UTC, brezinajn commented
> Looks like there's a conflict that will need to be resolved before we merge

Resolved

2023-12-03 10:53 UTC, JoelSpeed submitted a review, later dismissed

2023-12-03 10:53 UTC, JoelSpeed commented
Can we fix the linter issue please?

2023-12-17 08:54 UTC, tuunit commented
Hi @brezinajn,

Hope you are doing well. We would like to get this merged. The following linting issue is holding us back:
```bash
Error: oauthproxy.go:1205:9: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
	} else {
		return rawString
	}
```

2023-12-17 08:54 UTC, tuunit requested changes

2023-12-17 08:54 UTC, tuunit commented on oauthproxy.go
> +	}
```suggestion
	}
	return rawString
```

2023-12-19 13:47 UTC, brezinajn commented
> Hi @brezinajn,
> 
> Hope you are doing well. We would like to get this merged. The following linting issue is holding us back:
> 
> ```shell
> Error: oauthproxy.go:1205:9: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
> 	} else {
> 		return rawString
> 	}
> ```

Hi, sorry I'm on my vacation, so I'm not at my PC currently. Committed your suggestion. Hope it resolves the issue. Should there be another issue, please let me know. Thanks

2024-01-18 17:12 UTC, oshmyrko commented
Hi guys! Any updates on this?

2024-01-18 17:28 UTC, kvanzuijlen approved these changes

2024-01-18 17:29 UTC, kvanzuijlen commented
> Hi guys! Any updates on this?

This should be picked up during the next round of merging hopefully.

2024-01-20 19:06 UTC, JoelSpeed approved these changes

2024-01-20 19:08 UTC, merged