Update go-jose dependency as requested in #2350
oauth2-proxy/oauth2-proxy pull request #2356
Opened 2023-12-18 10:18 UTC by dasvh

Updating deprecated go-jose dependency (see: https://github.com/square/go-jose)

## Description

updated go-jose dependency by switching gopkg.in/square/go-jose.v2 with github.com/go-jose/go-jose/v3

## Motivation and Context

As recommended by the maintainer of `square/gojose`, I migrated to v3 of `go-jose/go-jose` for security fixes (see: https://github.com/advisories/GHSA-2c7c-3mj9-8fqh)

Relevant issue: https://github.com/oauth2-proxy/oauth2-proxy/issues/2350

---

Since `go-jose` is also used in `oauth2-proxy/mockoidc`, I also created a PR in that repository (https://github.com/oauth2-proxy/mockoidc/pull/47) which **should be merged before this PR** and would require an update on `oauth2-proxy/oauth2-proxy` as well.

2023-12-28 20:54 UTC, tuunit approved these changes
LGTM

2023-12-28 21:03 UTC, tuunit requested changes
Hi @dasvh,

Please add an entry for this PR to the `CHANGELOG.md`.

2023-12-29 16:33 UTC, dasvh commented
> Hi @dasvh,
> 
> Please add an entry for this PR to the `CHANGELOG.md`.

Thanks for the remark, I have updated the `CHANGELOG.md` accordingly. 

Did anyone have a chance to look at the the PR at [oauth2-proxy/mockoidc](https://github.com/oauth2-proxy/mockoidc/pull/47) which should be merged before this PR and would result in only one `go-jose` version being used and thus would require another commit removing the `gopkg.in/square/go-jose.v2 v2.6.0` entirely.

2024-01-06 11:54 UTC, tuunit approved these changes

2024-01-08 13:08 UTC, merged