Update ojg to latest release
oauth2-proxy/oauth2-proxy pull request #2357
Opened 2023-12-19 14:50 UTC by bitfehler

The previously used release is no longer available on Github.

## Description

When building the current master branch, I get the following error: 

```
pkg/providers/util/claim_extractor.go:14:2: reading github.com/ohler55/ojg/go.mod at revision v1.14.5: unknown revision v1.14.5
```

And indeed, the latest tag to be found over at [ojg](https://github.com/ohler55/ojg/tags?after=v1.17.4) is 1.15.0. This is obviously a tad strange, not sure how a tag would disappear, but I leave that judgement up to you. After this patch, oauth2-proxy builds fine for me.

## Motivation and Context

## How Has This Been Tested?

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

2023-12-28 21:02 UTC, tuunit requested changes
Hi @bitfehler,

please add an entry for this PR to the `CHANGELOG.md`

2024-01-03 20:13 UTC, bitfehler commented
Done

2024-01-06 11:53 UTC, tuunit approved these changes
LGTM

2024-01-08 11:41 UTC, JoelSpeed approved these changes

2024-01-08 11:49 UTC, merged