Feature/s390x option
oauth2-proxy/oauth2-proxy pull request #2734
Opened 2024-08-07 02:39 UTC by priby05

This PR simply adds the option of s390x as an architecture choice.

## Description

This change simply adds the option of s390x to both the Dockerfile and the dist.sh.

## Motivation and Context

Currently, we have an IBM Z mainframe that is trying to leverage the oauth proxy image in our kubernetes deployments but by default this does not allow Z (or s390x) architecture images.

## How Has This Been Tested?

I forked this repo and tested building, pushing and deploying this on our RHOCP cluster running on the IBM Z hardware. So the dependencies are not a problem on our hardware.

## Checklist:

- [X ] My change requires a change to the documentation or CHANGELOG.
- [X] I have updated the documentation/CHANGELOG accordingly.
- [X] I have created a feature (non-master) branch for my PR.
- [] I have written tests for my code changes.

2024-08-07 02:50 UTC, priby05 commented
You can test this by running a podman machine with qemu-user-static and the qemu s390x package installed. I then used a `podman build --platform linux/s390x .` command and pushed the image up to the github container registry (ghcr.io).

2024-08-07 14:50 UTC, tuunit commented
@priby05 I rebased the branch. Please add an entry to the changelog for your PR

2024-08-07 14:52 UTC, tuunit requested changes
LGTM. Changelog entry missing

2024-08-23 02:49 UTC, priby05 commented
Added changelog entry with commit 1ce0025

2024-08-23 06:19 UTC, tuunit approved these changes

2024-08-23 07:02 UTC, merged