[doc] Add example for caddy v2 forward_auth
oauth2-proxy/oauth2-proxy pull request #2759
Opened 2024-08-28 12:46 UTC by dabde

## Description

Add documentation to integrate oauth2 proxy with a caddy reverse proxy.

## Motivation and Context

It was from the caddy forward_auth example not clear how to use this with oauth2 proxy. Also in the context that this will be work under the same domain. So future people can use this example to faster find the solution.

Markdown syntax highlight is wrong, but the best fitting one for placeholder and comments.

## How Has This Been Tested?

Configuration is currently used with several protected endpoints. But this is only documentation for configuration of 3rd party reverse proxy. So no code changes.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [x] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

2024-08-28 12:50 UTC, tuunit commented
Hi @dabde, can you please add it to the v7.6 docs as well. That would be great.

2024-08-28 14:30 UTC, dabde commented
@tuunit Added also to version 7.6 documentation.

2024-08-28 21:26 UTC, tuunit approved these changes
LGTM

2024-08-28 21:31 UTC, tuunit requested changes

2024-08-28 21:31 UTC, tuunit commented on docs/docs/configuration/integration.md
> +## Configuring for use with the caddy v2 `forward_auth` directive
Build is failing because of broken link. Backticks can not be used in headers otherwise the HTML links cannot be properly generated

2024-08-28 21:31 UTC, tuunit commented on docs/versioned_docs/version-7.6.x/configuration/integration.md
> +## Configuring for use with the caddy v2 `forward_auth` directive
Same goes for this one

2024-08-28 22:10 UTC, dabde commented on docs/versioned_docs/version-7.6.x/configuration/integration.md
> +## Configuring for use with the caddy v2 `forward_auth` directive
Issue was line 270. fixed.

2024-09-15 04:23 UTC, polarathene reviewed
Typo and formatting fix suggestions + rephrasing the other statement a little.

The codefence is using tabs for indentation which seems a bit odd, but if that's the convention used elsewhere for the project docs no worries 👍

2024-09-15 04:23 UTC, polarathene commented on docs/docs/configuration/integration.md
> +The [Caddy `forward_auth` directive](https://caddyserver.com/docs/caddyfile/directives/forward_auth) allowes Caddy to authenticate requests via the oauth2-proxy's `/auth`.
```suggestion
The [Caddy `forward_auth` directive](https://caddyserver.com/docs/caddyfile/directives/forward_auth) allows Caddy to authenticate requests via the `oauth2-proxy`'s `/auth`.
```

2024-09-15 04:23 UTC, polarathene commented on docs/docs/configuration/integration.md
> +This example is for a simple reverse proxy setup where the `/oauth2/` path is kept under the same domain and failed auth `(status:401)` request will be catched and redirect to the `sign_in` endpoint.
```suggestion
This example is for a simple reverse proxy setup where the `/oauth2/` path is kept under the same domain and failed auth requests (401 status returned) will be caught and redirected to the `sign_in` endpoint.
```

2024-09-15 04:23 UTC, polarathene commented on docs/versioned_docs/version-7.6.x/configuration/integration.md
> +The [Caddy `forward_auth` directive](https://caddyserver.com/docs/caddyfile/directives/forward_auth) allowes Caddy to authenticate requests via the oauth2-proxy's `/auth`.
```suggestion
The [Caddy `forward_auth` directive](https://caddyserver.com/docs/caddyfile/directives/forward_auth) allows Caddy to authenticate requests via the `oauth2-proxy`'s `/auth`.
```

2024-09-15 04:23 UTC, polarathene commented on docs/versioned_docs/version-7.6.x/configuration/integration.md
> +This example is for a simple reverse proxy setup where the `/oauth2/` path is kept under the same domain and failed auth `(status:401)` request will be catched and redirect to the `sign_in` endpoint.
```suggestion
This example is for a simple reverse proxy setup where the `/oauth2/` path is kept under the same domain and failed auth requests (401 status returned) will be caught and redirected to the `sign_in` endpoint.
```

2024-09-23 14:34 UTC, merged