Fix relative URLs to configuration page
oauth2-proxy/oauth2-proxy pull request #2818
Opened 2024-10-15 07:22 UTC by bcremer

## Description

Fixes relative links to the configuration page from https://oauth2-proxy.github.io/oauth2-proxy/features/endpoints/

## Motivation and Context

Links are broken and return 404 pages.

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [x] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

2024-10-15 07:31 UTC, tuunit requested changes
Please add the same change to the docs/versioned_docs/v7.6.x and v7.7.x

2024-10-15 07:31 UTC, tuunit commented on docs/docs/features/endpoints.md
> +- /oauth2/auth - only returns a 202 Accepted response or a 401 Unauthorized response; for use with the [Nginx `auth_request` directive](../../configuration/integration#configuring-for-use-with-the-ng
Why did you add another traversal upwards `../`?

2024-10-28 20:01 UTC, tuunit requested changes
@bcremer are you going to apply the requested changes?

2024-10-28 20:01 UTC, tuunit commented on docs/docs/features/endpoints.md
> +- /oauth2/auth - only returns a 202 Accepted response or a 401 Unauthorized response; for use with the [Nginx `auth_request` directive](../../configuration/integration#configuring-for-use-with-the-ng
I tested it locally. The additional traversal is unnecessary.

2024-10-29 06:18 UTC, bcremer commented
> Please add the same change to the docs/versioned_docs/v7.6.x and v7.7.x

Fixed.

2024-10-29 15:17 UTC, tuunit approved these changes

2024-10-29 15:21 UTC, merged