Related to issue #2887
oauth2-proxy/oauth2-proxy pull request #2888
Opened 2024-12-19 15:33 UTC by stomekpe

Change the jwttoken Regex 

## Description

Update jwt_session.go to just validate if each part of jwt token  with {
## Motivation and Context
Update jwt_session.go to just validate if each part of jwt token  with { 
Solve the issue:
https://github.com/oauth2-proxy/oauth2-proxy/issues/2887

## How Has This Been Tested?

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.
- [ ] I have written tests for my code changes.

2025-01-08 20:04 UTC, tuunit requested changes
Please add a `CHANGELOG.md` entry

2025-01-13 09:10 UTC, stomekpe commented
> Please add a `CHANGELOG.md` entry

Done

2025-01-15 08:01 UTC, tuunit submitted a review, later dismissed

2025-01-15 08:03 UTC, tuunit approved these changes

2025-01-15 08:06 UTC, merged