Unable to correctly redirect with a url(like) value in the query string
oauth2-proxy/oauth2-proxy pull request #790
Opened 2020-09-23 16:08 UTC by ScottGuymer

## Description

When redirecting to the final destination, if the URL had a URL(like) value in the query string it would fail and redirect to /

To fix this I corrected the regex to anchor at the start of the string being checked so it does not detect the URL in the query string and fail the test.

## Motivation and Context

It is possible that when redirecting to a location with a query string it may contain a url like value. To ensure that the redirect works correctly it is necessary to ignore any values in the query string that do not meet the regex in `invalidRedirectRegex`

## How Has This Been Tested?

Added additional cases to the unit testing to cover this scenario

## Checklist:

- [ ] My change requires a change to the documentation or CHANGELOG.
- [ ] I have updated the documentation/CHANGELOG accordingly.
- [ ] I have created a feature (non-master) branch for my PR.

2020-09-23 16:08 UTC, ScottGuymer commented
fixes #786

2020-09-23 18:34 UTC, ScottGuymer commented
Looks like this changes breaks a lot of the test urls in `test/openredirects.txt` in that it is expected that they all fail the valid url check but with this change some of them now pass

2020-09-24 00:59 UTC, NickMeves requested changes

2020-09-24 00:59 UTC, NickMeves commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
We can't anchor this regex (see the comment for a brief explanation). Here's the published CVE: https://github.com/oauth2-proxy/oauth2-proxy/security/advisories/GHSA-5m6c-jp6f-2vcv

What sort of URLs is this failing for you with? Do you have an example so I can visualize the problem better?

I think the solution will involve more meat to the `invalidRedirect` check -- likely needing a whole method that can split on querystring parts that are giving you problems.

2020-09-24 06:52 UTC, ScottGuymer commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
After the test failed I did some reading on open redirects. I can see why this protection is here.

In our case our URLs look just like this `https://foo.bar/redirect?param=https://evil.com/path|12345`

We have a query string that describes a scheme url for a value and its value separated by `|`.

It would be difficult to be able to add the URL in use to the whitelist (its not even always a URL) as it is arbitrary. 

Do you think its possible to allow these types of URLS and still be safe against open redirects?

Now we have a workaround of encoding the parameter. But this adds complexity for anyone integrating with our solution which we would rather avoid if possible.

2020-09-26 11:33 UTC, JoelSpeed commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
I had a play with this just now, by using the local environment and substituting the image for `quay.io/pusher/oauth2_proxy:v5.0.0`. I was able to reproduce a bunch of the redirects but adding a `?` (URL encoded as `%3f`) into them in various places didn't seem to allow the redirect. So I wonder if we may actually be ok if we somehow ignore the query string part of and redirect that we are given?

I think we should try and do some research to see if this is a known thing about open redirects, it may be known to be safe

2020-09-30 14:40 UTC, ScottGuymer commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
Where did you add the `?`? 

Any suggestions on where i can do the research?

2020-10-02 18:29 UTC, JoelSpeed commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
>Where did you add the ?

At various places through the URL but crucially before anywhere that the regex we currently have would have matched

> Any suggestions on where i can do the research?

Nothing off the top of my head, I was just going to try googling the topic over the weekend 😅

2020-10-06 17:10 UTC, ScottGuymer commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
Im not sure where to go with this PR now. 
I created a regexr to test and see if we can come up with a better regex that will catch redirects and allow for our use case.

https://regexr.com/5df9t

2020-11-23 08:13 UTC, ScottGuymer commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
@JoelSpeed can you point me in the right direction here?

At the moment we are using my fork but want to get this fixed upstream too.

2020-11-26 18:51 UTC, JoelSpeed commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
I'm still not entirely sure if we can ignore the query string, but from my testing it seemed that way.

If that's the case, my suggestion would be to just split the redirect on `?` before it enters filtering stage, so that only the core part of the URL minus the query string is checked to be valid. That feels like it would be easier than trying to adapt the regex. Basically we would do a strings.Split at the top of `IsValidRedirect`.

@NickMeves Not sure if you ever did any testing of this, or whether you are aware if we can ignore the query string on a redirect?

2020-11-26 21:24 UTC, NickMeves commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
I'm still uncomfortable making that change without having full confidence we are safe.

There's several querystring examples in the open redirect test cases files. I don't know the full background in how those test cases could be exploited.

2020-11-27 17:04 UTC, JoelSpeed commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
Do you mean ones like
```
/redirect?url=/\/example.com&next=/\/example.com&redirect=/\/example.com&redir=/\/example.com&rurl=/\/example.com&redirect_uri=/\/example.com
```
I think this manages to override DOM elements in JS, it may not actually be a problem for a redirect response like we provide, but we should try it out and eliminate cases that may be false in our scenario. Wish there was an easy way to automate this 🤔

2020-11-27 17:12 UTC, NickMeves commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
```
javascript://www.whitelisteddomain.tld?%a0alert%281%29
http://google.com:80?@www.whitelisteddomain.tld/
/?url=//example.com&next=//example.com&redirect=//example.com&redir=//example.com&rurl=//example.com&redirect_uri=//example.com
/?url=/\/example.com&next=/\/example.com&redirect=/\/example.com&redirect_uri=/\/example.com
/?url=Https://example.com&next=Https://example.com&redirect=Https://example.com&redir=Https://example.com&rurl=Https://example.com&redirect_uri=Https://example.com
/redirect?url=//example.com&next=//example.com&redirect=//example.com&redir=//example.com&rurl=//example.com&redirect_uri=//example.com
/redirect?url=/\/example.com&next=/\/example.com&redirect=/\/example.com&redir=/\/example.com&rurl=/\/example.com&redirect_uri=/\/example.com
/redirect?url=Https://example.com&next=Https://example.com&redirect=Https://example.com&redir=Https://example.com&rurl=Https://example.com&redirect_uri=Https://example.com
/ReceiveAutoRedirect/false?desiredLocationUrl=http://xssposed.org
javascript://www.whitelisteddomain.tld?%a0alert%281%29
http://localdomain.pw:80?@www.whitelisteddomain.tld/
//localdomain.pw:80?@www.whitelisteddomain.tld/
javascript://https://www.whitelisteddomain.tld/?z=%0Aalert(1)
javascript://example.com?%a0alert%281%29
http://google.com:80?@example.com/
//google.com:80?@example.com/
javascript://https://example.com/?z=%0Aalert(1)
```

2020-11-27 17:16 UTC, NickMeves commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
I'm more curious to understand the extent of the user base that is affected by this and if there's a viable workaround on their end in configuration before we look to weaken our open redirect controls.

For instance, if they included their full domain in the `rd` or header they are using for the redirect, this is not a problem. The regex only checks on relative paths with a leading `/`.

2021-01-28 08:45 UTC, ScottGuymer commented on oauthproxy.go
> +	invalidRedirectRegex = regexp.MustCompile(`^[/\\](?:[\s\v]*|\.{1,2})[/\\]`)
In reality its probably quite a small use case. 
The regex seems to reject any url that is in the query string and we use url based namespaces as identifier schemas to access resources in our application. And these could be any url so we cant really add a generic exclusion list for them.

The one workaround that we have found is to URL encode the value which then defeats this check. (not sure if this is a security hole in itself)

2021-02-05 00:14 UTC, closed without merging